# Generated by Django 6.0.2 on 2026-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(help_text='Nombre visible de la tienda o taller.', max_length=150, verbose_name='nombre de la tienda')),
                ('subdominio', models.SlugField(help_text='Subdominio único para esta tienda (ej: "mitaller"). Solo letras minúsculas, números y guiones.', max_length=63, unique=True, verbose_name='subdominio')),
                ('comuna_base', models.CharField(help_text='Comuna donde opera principalmente la tienda.', max_length=100, verbose_name='comuna base')),
                ('taller_fisico', models.BooleanField(default=True, help_text='Indica si la tienda cuenta con un local físico.', verbose_name='tiene taller físico')),
                ('scraping_activado', models.BooleanField(default=False, help_text='Habilita el scraping automático de precios para esta tienda. Requiere configuración adicional de Celery y Playwright.', verbose_name='scraping activado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
                'ordering': ['nombre_tienda'],
                'indexes': [models.Index(fields=['subdominio'], name='tenant_app__subdomi_786932_idx'), models.Index(fields=['scraping_activado'], name='tenant_app__scrapin_3c1bdb_idx')],
            },
        ),
    ]
