# Generated by Django 6.0.2 on 2026-02-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del producto/servicio.', max_digits=10, verbose_name='precio base')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0.0, help_text='Margen de ganancia aplicado al precio base (ej: 15.50 para 15.5%).', max_digits=5, verbose_name='margen de ganancia')),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Atributos dinámicos del producto (colores, tamaños, características extra).', verbose_name='metadatos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tienda', models.ForeignKey(help_text='Tienda a la que pertenece este producto.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tenant_app.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'producto de tienda',
                'verbose_name_plural': 'productos de tienda',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tienda'], name='tenant_app__tienda__7d1623_idx')],
            },
        ),
    ]
