# Generated by Django 6.0.2 on 2026-02-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_productotienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competidor_nombre', models.CharField(help_text='Ej: Imprenta Okey, Gráfica VM', max_length=150, verbose_name='nombre del competidor')),
                ('producto_referencia', models.CharField(help_text='URL o nombre exacto del producto en el sitio del competidor', max_length=255, verbose_name='referencia del producto')),
                ('precio_extraido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio base extraído')),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de extracción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_radar', to='tenant_app.productotienda', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'radar de precio',
                'verbose_name_plural': 'radares de precios',
                'ordering': ['-fecha_extraccion'],
                'indexes': [models.Index(fields=['producto', '-fecha_extraccion'], name='tenant_app__product_b58464_idx')],
            },
        ),
    ]
