# Generated by Django 6.0.2 on 2026-02-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_radarprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='mp_access_token',
            field=models.CharField(blank=True, help_text='Token OAuth necesario para cobrar a su nombre u operar pagos de forma delegada.', max_length=255, null=True, verbose_name='access token de Mercado Pago'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='mp_vendedor_id',
            field=models.CharField(blank=True, help_text='ID de usuario del subcontratista en Mercado Pago para recibir Split de Pagos.', max_length=255, null=True, verbose_name='ID de vendedor en Mercado Pago'),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto total pagado')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='estado del pago')),
                ('mp_payment_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID de pago MP')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='nombre del cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='email del cliente')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asociadas', to='tenant_app.productotienda', verbose_name='producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='tenant_app.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tienda', '-creado_en'], name='tenant_app__tienda__13cacc_idx'), models.Index(fields=['estado_pago'], name='tenant_app__estado__a38512_idx'), models.Index(fields=['mp_payment_id'], name='tenant_app__mp_paym_0d291e_idx')],
            },
        ),
    ]
