# Generated by Django 6.0.2 on 2026-02-24 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0004_tienda_mp_access_token_tienda_mp_vendedor_id_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario de Django que administra este taller.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to=settings.AUTH_USER_MODEL, verbose_name='usuario administrador'),
        ),
    ]
