# Generated by Django 6.0.2 on 2026-02-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_tienda_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplimiento_plazos', models.FloatField(default=5.0, help_text='Puntuación de 0 a 5 por entregar a tiempo.')),
                ('calidad_impresion', models.FloatField(default=5.0, help_text='Puntuación de 0 a 5 por calidad del producto final.')),
                ('tasa_retorno', models.FloatField(default=0.0, help_text='Porcentaje de trabajos devueltos o rechazados.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printscore', to='tenant_app.tienda')),
            ],
        ),
    ]
