# Generated by Django 6.0.2 on 2026-03-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_printscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='aprobada',
            field=models.BooleanField(default=False, help_text='Indica si la tienda fue revisada y autorizada por la administración central para operar.', verbose_name='aprobada por admin'),
        ),
    ]
