# Generated by Django 6.0.2 on 2026-03-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_tienda_aprobada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre de la comuna')),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre de la provincia')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre de la región')),
                ('orden', models.IntegerField(default=0, verbose_name='orden geoespacial')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='comuna_base',
        ),
        migrations.AddField(
            model_name='tienda',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna donde opera principalmente la tienda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='tenant_app.comuna', verbose_name='comuna base'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='tenant_app.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='tenant_app.region'),
        ),
    ]
