# Generated by Django 6.0.2 on 2026-03-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0008_comuna_provincia_region_remove_tienda_comuna_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre de producto')),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio real (costo proveedor) extraído vía scraping.', max_digits=10, verbose_name='precio de costo')),
                ('categoria', models.CharField(default='General', max_length=100, verbose_name='categoría')),
                ('origen_url', models.URLField(blank=True, null=True, verbose_name='url origen scraper')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='productotienda',
            name='producto_global',
            field=models.ForeignKey(blank=True, help_text='Referencia al producto maestro del que heredó este artículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='tenant_app.productoglobal'),
        ),
    ]
